#----------------------------------------------------------------------
# This file was generated by .\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAA2lJ"
    "REFUWIWtV89LVFEU/u6MlNM8KiJcTdSigUJy0cKUgoSeZq5qMWC1GO3N2KZIiCBwkf+BRSkk"
    "M6GLUhgQgiLTR1j0QjdRwiAYmUMUpbOIuPMj0fdajHPn3fd7Br/N3HfuPef73rnn3HeHoEoI"
    "clLTP+fj96AeOwLhdi/oyMQ4puSeauLV1ULKoX4XsE8ojafkqCAnowCgampPvj0+7hbb5zQZ"
    "lBNzjuQA9jwcsA5MfGNuvoBDBrw4M+SL2FxYdIxDRYlYzVtmoCpyAHj9AcWBB45L7GKaBBgX"
    "psMi0mERl/cfso/+b6P0291ZtQjitCAdFk1BGr/IJhsVpbK/owDdesbLMhCUE3NenI2i9OQ0"
    "kfIkQA8mgICc9epkyozYUvqdnAZtl0A7Yo7++kz7jAYrrKysQFEULv3psAh/sbT3wt14ZbEG"
    "QNVYZtzgeA6Ukc1m0ddQAMDXwOKJLjamogTU7y4JkpNAMOAoovzSngQ0Nzdzz3oRmUymEvTF"
    "CCtE4fkjL6Hhq7rnt/Fnc4ONR9cCXBHSC9c9x/FZtVoZjcuzbDxRaODmTn97Z1ovxCKgw08h"
    "vHpcMridC7OJIR9g3e8AAFI5JpqamhyDUVGCli8gGL0E2h4DvXIHQizi6ANC+kkmk2FbYHXI"
    "GAUaOwEAFEVhRWoUBTgfUFwR2mXCStji0XO2QY3k9P44qChZdoXpa5gOi7j18zPk3DpnVxQF"
    "oVAIo2sB9DUU4N/eHqLbJo3mkbt4k7WjUYjVM7cFRgz+XkLq7w/OlgydREvgACesnH7uDSMd"
    "QGqmVIiT08zsP9WErYVFoLsTwrVIG1ldXR0jhETtRDhBURQA4Pafieg6A+wVuEKkiRQTI8hJ"
    "UFEq5c8pC9WQ60XYFd7m+48oflqCcOMqqCgRT3dCK2I7cjcUB4e586EOAI4vz/Qk1oNjZWNr"
    "aysIISCEQNM0zM/PQ1VVT8Qbz166H0CxCLsT1AFAvj0+3icnmQB8fcN7HHR9sYqAJ1O26Vd/"
    "Z4HwYc7meCPyAqvethNARancFeYbUa0wkbmkX08OGDKwHbCmr2P5S6hvO21rC8TvZ+Pc+T4T"
    "p+VdvVYReuR6B6B9/2U0m/gsBeyUCF192PLYTuyUELt/RJ4F1CrEjbhqAZyY2cQQCOnnjCra"
    "aIf0ttpY/wH4wW8mIVHhigAAAABJRU5ErkJggg==")

